### ISSUE TITLE
[Bug] Windows binaries do not work

### ISSUE THREAD

**Issue by boomzero** [boomzero/quicksubmit#10]
**Describe the bug** 

Windows binaries do not work

**To Reproduce** Steps to reproduce the behavior: 

run `quickSubmit` on Windows

**Expected behavior** 

Execution without errors.

**Additional context** Add any other context about the problem here.
```
thread 'main' panicked at runtime\ops\runtime.rs:24:45:
called `Result::unwrap()` on an `Err` value: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at C:\a\deno\deno\runtime\tokio_util.rs:103:36:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)thread 'main' panicked at runtime\ops\runtime.rs:24:45:
called `Result::unwrap()` on an `Err` value: ()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at C:\a\deno\deno\runtime\tokio_util.rs:103:36:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)
```

**Comment by boomzero** [comment]
Okay it turns out windows separates file paths with `\`...
